### PR TITLE
Feature/initializing single models

### PR DESCRIPTION
**Pull request by scottdomes**
-If a model is loading, initialize will not do an Object.assign (thus avoiding an invariant failure with mobx)
-If the data is null, model will still be initialized (allows us to work with empty addresses, for example)

### CODE REVIEW

**Comment by colinjfw** [comment]
Interesting, thanks for the update! Would we want to implement an 'observableAssign' method? The idea for that assign was to make sure that the model always contains the latest version of data. We could now be in a position where an 'initialized' model doesn't contain the latest information sent from the backend.

Does that make sense? Maybe we could use your assignGettersAndSetters method here.

**Comment by scottdomes** [comment]
Right now we're trusting that if the model is loading, that data will be
properly loaded in when loading completes, so we can skip the assign until
then AKA trusting a proper implementation of retrieve. We could make
retrieve more magical and have it automatically take care of the assign
behind the scenes.

Right now the flow for retrieve is almost always the same- create a schema,
parse the raw data, do an Object.assign. So one could make an argument for
generalizing that.

**Comment by colinjfw** [comment]
What about data that's loaded through a collection? The schema will call `initialize` but it won't end up actually updating the data, should this be handled inside the schema?

**Comment by scottdomes** [comment]
But then wouldn't the loading flag be false on the model being initialized?

**Pull request merged**
