### PR TITLE
Feature/singletons

### PR DESCRIPTION
**Pull request by scottdomes**

### CODE REVIEW

**Comment by colinjfw** [comment]
I get the idea, however the only worry I have is that the singleton isn't an instance of a model. It's just turned into a basic observable object. This also means you cannot use the Schema object to parse the data you get.

What if the `_result` was an instance of the model?

**Comment by scottdomes** [comment]
A good point. Fixed.

**Comment by colinjfw** [comment]
If I have nested models on the data being loaded would I be able to populate those by using a Schema? I'm just wondering about the `assignGettersAndSetters` call in the load function, I'm assuming it will overwrite the nested models.

**Comment by scottdomes** [comment]
`assignGettersAndSetters` does not actually modify the _results in anyway, just makes the attributes accessible. Someone could use one of the `setters` to overwrite a nested model (e.g. `collab.influencer = {}`) but I'm not sure how we could prevent that in any case. I tested it with a nested Impressions model within a Singleton instance of the Brand model and the Impressions model was still present (e.g. brand.impressions returned an instance of the ImpressionsModel).

But I'll continue to test it and iterate on it as we go forward with refactoring.

**Comment by colinjfw** [comment]
My comments on the 'Singleton' object, as discussed:
- We don't have the model's methods when we load the model through the singleton
- We can potentially fix some of the issues that the singleton solves by using the approach discussed in the readme.

I do understand the problem it's trying to solve though, I think we should keep working on this. @spruceberry @dalemeonsah any idea?

I'll merge this and we can keep experimenting from there.

**Pull request merged**
